#!/bin/sh
this is hello world, Jenkins
echo This is my project 1 job
print('==================== start ========================')
print('===================================================')
file = open('example.txt', 'w+')
print('==================== writing file =================')
file.write('I am a file created by freestyle job')
file.close()
print('===================================================')
print('==================== end ==========================')
